---
- name: Install and start Jenkins
  hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-21-jre
        state: present

    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt: 
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd: 
        name: jenkins
        state: started
        enabled: yes

    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Allow Jenkins port through UFW
      ufw:
       rule: allow
       port: 8080
       proto: tcp

    - name: Enable UFW
      ufw:
       state: enabled
       policy: allow

    - name: Allow Jenkins user to run sudo without a password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^jenkins ALL=\(ALL\) NOPASSWD:ALL'
        line: 'jenkins ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'

# 👇 Read and print password
    - name: Read Jenkins initial admin password
      ansible.builtin.slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_pass

    - name: Show Jenkins initial admin password
      ansible.builtin.debug:
        msg: "Jenkins Initial Admin Password is: {{ jenkins_admin_pass.content | b64decode }}"
